build: Fixes on gcc-8, defining cycle_T
Additional gcc-8 checks make ktap to fail to build, since cycle_t is undefined
and gcc-8 was picky, showing:

	..ktap/runtime/kp_transport.c:120:29: error: unknown type name ‘cycle_t’; did you mean ‘cycles_t’?
	 unsigned long long ns2usecs(cycle_t nsec)
				     ^~~~~~~
				     cycles_t
	../ktap/runtime/kp_transport.c: In function ‘trace_print_timestamp’:
	../ktap/runtime/kp_transport.c:133:6: error: implicit declaration of function ‘ns2usecs’ [-Werror=implicit-function-declaration]
	  t = ns2usecs(iter->ts);
	      ^~~~~~~~